name: zard_http
description: A safe, model-less HTTP networking library for Dart that eliminates boilerplate while ensuring strict validation at the edges.
version: 0.2.0
repository: https://github.com/aleclarson/zard_http

environment:
  sdk: ">=3.3.0 <4.0.0"

dev_dependencies:
  test: ^1.24.0
dependencies:
  http: ^1.6.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  zard: ^0.0.26
