name: zard_http
description: Under construction
version: 0.1.1
repository: https://github.com/aleclarson/zard_http

environment:
  sdk: ">=3.3.0 <4.0.0"

dev_dependencies:
  test: ^1.24.0
dependencies:
  http: ^1.6.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  zard: ^0.0.26
